version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile/Dockerfile-php
    ports:
      - "8000:80"
    container_name: todo_web
    volumes:
      - ./project:/var/www/public
      - ./apache-config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - phpmyadmin
    networks:
      - todo-net

  db:
    build:
      context: .
      dockerfile: ./Dockerfile/Dockerfile-db
    container_name: mysql_db_container
    ports:
      - "3306:3306"
    volumes:
      - todo-db:/var/lib/mysql
    networks:
      - todo-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    networks:
      - todo-net

networks:
  todo-net:

volumes:
  todo-db:
