FROM mysql:latest

# Установка переменных окружения для MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=todo_list

# Экспонирование порта MySQL (не обязательно, если вы не собираетесь подключаться к MySQL извне контейнера)
EXPOSE 3306

# Выполняем команду CMD, чтобы задать дополнительные параметры для entrypoint
CMD ["mysqld"]